# -*- encoding: utf-8 -*-

require "unicode_utils/version"
require "unicode_utils/name"
require "unicode_utils/simple_upcase"
require "unicode_utils/simple_downcase"
require "unicode_utils/upcase"
require "unicode_utils/downcase"
require "unicode_utils/titlecase_char_q"
require "unicode_utils/lowercase_char_q"
require "unicode_utils/uppercase_char_q"
require "unicode_utils/cased_char_q"
require "unicode_utils/case_ignorable_char_q"
require "unicode_utils/soft_dotted_char_q"
require "unicode_utils/combining_class"
require "unicode_utils/hangul_syllable_decomposition"
